catalog/urls.py
from django.urls import path, include
from catalog.views import catalog, info

app_name = 'catalog' # чтобы использовать в тегах catalog:название_функции

urlpatterns = [
    path('', catalog, name='catalog'),
    path('info/', info, name='info'), 
]

englishSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('new_order/', include('orders.urls')),
    path('products/', include('products.urls')),
    path('home/', include('users.urls')),
    path('api/', include('myapi.urls')),
    path('accounts/', include('django.contrib.auth.urls')) ,
    path('__debug__/', include('debug_toolbar.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='home'), # ??????
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapi/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
# """ Маршрутизатор REST Framework будет следить за тем, чтобы наши запросы динамически попадали в нужный ресурс. 
# Если мы добавим или удалим элементы из базы данных, URL-адреса обновятся, чтобы соответствовать."""
router.register(r'products', views.ProductViewSet)
router.register(r'categories', views.CategoryViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

products/urls.py
from django.urls import path
from products.views import new_product, ex_category, ex_product

app_name = 'products'

urlpatterns = [
    path('new/', new_product, name='new'),
    path('<int:product_id>/', ex_product, name='ex_product'), # параметризированный маршрут 
    path('<int:category_id>', ex_category, name='ex_category'),
]

users/urls.py
from django.urls import path
from .views import home, SignUp, users_list

app_name = 'users'

urlpatterns = [
    path('', home, name="home"),
    path("signup/", SignUp.as_view(), name="signup"),
    path('users/', users_list, name='users'),
]

""" 
Urls, предоставляемые приложением auth

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""

catalog/models.py
from django.db import models

# Create your models here.

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import logging

from products.models import Product, Category

logger = logging.getLogger(__name__) # error, warning, critical

def catalog(request):
	""" Главная страница """
	AMOUNT_OF_PRODUCTS = 50
	if request.GET.get('selecter', False) not in ("None", False):
		sort_name = str(request.GET.get('selecter', False))
		products = Product.published.order_by(sort_name)[:AMOUNT_OF_PRODUCTS] # Используется менеджер published. Подробнее написано в моделях.
	else:
		products = Product.published.all()[:AMOUNT_OF_PRODUCTS]
	categories = Category.objects.all().order_by("name")
	context = {
		"products":products,
		"categories":categories,
		}
	return render(request, "catalog/catalog.html", context)

def info(request):
	context = {}
	return render(request, 'catalog/information.html', context)

'''
Аналогичным образом, самый простой способ ограничить доступ к зарегистрированным пользователям в 
ваших представлениях на основе классов - это производные от LoginRequiredMixin. 
Вы должны объявить этот mixin сначала в списке суперкласса, перед классом основного представления.
from django.contrib.auth.mixins import LoginRequiredMixin

class MyView(LoginRequiredMixin, View):
    ...
Это имеет такое же поведение при переадресации, что и login_required декоратор. 
Вы также можете указать альтернативное местоположение для перенаправления пользователя, если он не
 аутентифицирован (login_url), и имя параметра URL вместо "next" , чтобы вставить текущий абсолютный 
 путь (redirect_field_name).

class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    
# Еще одна причина перейти на GET, это то, что GET не должен
# использоваться с методами, которые меняют состояние сервера, 
# а только для read-only операций.

# git add -i
# limit_choices_to={'is_staff': True})

'''

catalog/templates/basic.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
        <title>{% block title %}Главная{% endblock %}- Магазин</title>
        <link rel="stylesheet" type="text/css" href="{% static 'catalog/style.css' %}">
    </head>
    <body>
        <header>
            <h1>{% block page_title %}{% endblock %}</h1>
            <hr>
        </header>
        <nav>
            <a href="{% url 'catalog:catalog' %}"><li>Главная</li></a>
            <a href="{% url 'products:new' %}"><li>Добавить товар</li></a>
            <a href="/admin/"><li>Админ панель</li></a>
            <a href="{% url 'catalog:info' %}"><li>Функции для авторизованных пользователей</li></a> 
            <a href="{% url 'users:home' %}"><li>Личный кабинет</li></a>
            <hr>
            
            <p1>Здравствуйте, </p1>
            <a href="{% url 'users:home' %}"><b>{{ user.username|default:'Guest' }}</b></a>
            <hr>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><li>Выйти</li></a>
            {% else %}
                <a href="{% url 'login' %}"><li>Войти</li></a>
                <a href="{% url 'users:signup' %}"><li>Регистрация</li></a>
            {% endif %}
        </nav>
        <section>
            {% block content %}
            {% endblock %}
        </section>
    </body>
</html>