catalog/urls.py
from django.urls import path, include
from catalog.views import catalog, info

app_name = 'catalog' # чтобы использовать в тегах catalog:название_функции

urlpatterns = [
    path('', catalog, name='catalog'),
    path('info/', info, name='info'), 
]

englishSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('new_order/', include('orders.urls')),
    path('products/', include('products.urls')),
    path('home/', include('users.urls')),
    path('api/', include('myapi.urls')),
    path('accounts/', include('django.contrib.auth.urls')) ,
    path('__debug__/', include('debug_toolbar.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='home'), # ??????
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapi/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
# """ Маршрутизатор REST Framework будет следить за тем, чтобы наши запросы динамически попадали в нужный ресурс. 
# Если мы добавим или удалим элементы из базы данных, URL-адреса обновятся, чтобы соответствовать."""
router.register(r'products', views.ProductViewSet)
router.register(r'categories', views.CategoryViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

products/urls.py
from django.urls import path
from products.views import new_product, ex_category, ex_product

app_name = 'products'

urlpatterns = [
    path('new/', new_product, name='new'),
    path('<int:product_id>/', ex_product, name='ex_product'), # параметризированный маршрут 
    path('<int:category_id>', ex_category, name='ex_category'),
]

users/urls.py
from django.urls import path
from .views import home, SignUp, users_list

app_name = 'users'

urlpatterns = [
    path('', home, name="home"),
    path("signup/", SignUp.as_view(), name="signup"),
    path('users/', users_list, name='users'),
]

""" 
Urls, предоставляемые приложением auth

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""

catalog/models.py
from django.db import models

# Create your models here.

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import logging

from products.models import Product, Category

logger = logging.getLogger(__name__) # error, warning, critical

def catalog(request):
	""" Главная страница """
	AMOUNT_OF_PRODUCTS = 50
	if request.GET.get('selecter', False) not in ("None", False):
		sort_name = str(request.GET.get('selecter', False))
		products = Product.published.order_by(sort_name)[:AMOUNT_OF_PRODUCTS] # Используется менеджер published. Подробнее написано в моделях.
	else:
		products = Product.published.all()[:AMOUNT_OF_PRODUCTS]
	categories = Category.objects.all().order_by("name")
	context = {
		"products":products,
		"categories":categories,
		}
	return render(request, "catalog/catalog.html", context)

def info(request):
	context = {}
	return render(request, 'catalog/information.html', context)

'''
Аналогичным образом, самый простой способ ограничить доступ к зарегистрированным пользователям в 
ваших представлениях на основе классов - это производные от LoginRequiredMixin. 
Вы должны объявить этот mixin сначала в списке суперкласса, перед классом основного представления.
from django.contrib.auth.mixins import LoginRequiredMixin

class MyView(LoginRequiredMixin, View):
    ...
Это имеет такое же поведение при переадресации, что и login_required декоратор. 
Вы также можете указать альтернативное местоположение для перенаправления пользователя, если он не
 аутентифицирован (login_url), и имя параметра URL вместо "next" , чтобы вставить текущий абсолютный 
 путь (redirect_field_name).

class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    
# Еще одна причина перейти на GET, это то, что GET не должен
# использоваться с методами, которые меняют состояние сервера, 
# а только для read-only операций.

# git add -i
# limit_choices_to={'is_staff': True})

'''

catalog/templates/catalog/catalog.html
{% extends "basic.html" %}

{% block title %}
Магазин
{% endblock %}

{%  block page_title %}
Магазин
{% endblock %}

{% block content %}
    <h1>Категория: {{ current_cat.name_with_quotes }}</h1> 
    {% for cat in categories %}
        {% if cat.pk != current_cat.pk %}
            <a href="{% url 'products:ex_category' cat.pk %}">{{ cat.name }}</a>
        {% endif %}
    {% endfor %}
    {{ cat.name }}
    <hr>
    <h1>Все товары:</h1>
    {% if user.is_authenticated %}
        <p>Фильтр по:</p>
        <form action="{% url 'catalog:catalog' %}" method="get"> 
            <select name="selecter">
                <option value="None">--------</option>
                <option value="name">Названию</option>
                <option value="category">Категории</option>
                <option value="price">Цене</option>
              </select>
              <button type="submit" value="Применить">Применить</button>
        </form>
        <form action="{% url 'catalog:catalog' %}" method="get"> 
            <button type="submit" value="Сбросить">Сбросить</button>
        </form>
    {% endif %}
    <hr>
    {% for product in products %}
        <h2> <a href="{% url 'products:ex_product' product.pk %}"> {{ product.name }} </a>  
            <h2> {{ product.price }}₽ </h2>
            <h5> <a href="{% url 'users:users' %}">(by {{ product.seller }}) [{{ product.add_date|date:"d M, Y" }}]</a></h5>
         </h2>  <p2>{{ product.category }} <br></p2>
        <hr>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/information.html
{% extends "basic.html" %}

{% block title %}
Информация
{% endblock %}

{%  block page_title %}
Функции, доступные зарегестрированным пользователям:
{% endblock %}

{% block content %}
<h2> <li>Добавление новых товаров</li></h2>
<hr>
<h2> <li>Просмотр своего личного списка добавленных товаров</li></h2>
<hr>
<h2> <li>Возможность продавать товары другим пользователям</li></h2>
<hr>

{% endblock %}